import { Injectable } from '@nestjs/common';
import { MfaChannelAdapter, MfaChannel } from '../mfa-channel.interface';
import { MfaService } from '../../mfa.service';

@Injectable()
export class TotpAdapter implements MfaChannelAdapter {
  readonly canal: MfaChannel = 'totp';

  constructor(private mfaService: MfaService) {}

  async sendCode(): Promise<void> {
    // TOTP: code is generated by the user's authenticator app, no code to send
  }

  async verifyCode(params: {
    utilisateurId: string;
    code: string;
    storedSecret?: string | null;
  }): Promise<boolean> {
    if (!params.storedSecret) return false;
    return this.mfaService.verifyTotp(params.storedSecret, params.code);
  }
}
